name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./mywebsite
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mywebsite:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode PEM file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > key.pem

      - name: Set permissions for PEM file
        run: chmod 600 key.pem

      - name: Deploy to server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@ec2-54-252-213-83.ap-southeast-2.compute.amazonaws.com"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/mywebsite:latest &&
            sudo docker stop mywebsite-container || true &&
            sudo docker rm mywebsite-container || true &&
            sudo docker run -d --name mywebsite-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/mywebsite:latest
          "
